<a href="https://colab.research.google.com/github/bricemeudec/projet-Energie/blob/main/projet_energie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Monter le lecteur Drive où sont stockées les données

In [3]:
import pandas as pd

Lire les données du CSV

In [4]:

energie = pd.read_csv("eco2mix.csv", sep = ";")
energie.head()

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_11732\1829544524.py:1: DtypeWarning: Columns (0: Eolien (MW)) have mixed types. Specify dtype option on import or set low_memory=False.
  energie = pd.read_csv("eco2mix.csv", sep = ";")

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
0,76,Occitanie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,53,Bretagne,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,Île-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28,Normandie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32,Hauts-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

lire les première lignes

In [5]:
energie.info()

<class 'pandas.DataFrame'>
RangeIndex: 2803968 entries, 0 to 2803967
Data columns (total 32 columns):
 #   Column               Dtype
---  ------               -----
 0   Code INSEE région    int64
 1   Région               str
 2   Nature               str
 3   Date                 str
 4   Heure                str
 5   Date - Heure         str
 6   Consommation (MW)    float64
 7   Thermique (MW)       float64
 8   Nucléaire (MW)       float64
 9   Eolien (MW)          object
 10  Solaire (MW)         float64
 11  Hydraulique (MW)     float64
 12  Pompage (MW)         float64
 13  Bioénergies (MW)     float64
 14  Ech. physiques (MW)  float64
 15  Stockage batterie    float64
 16  Déstockage batterie  float64
 17  Eolien terrestre     float64
 18  Eolien offshore      float64
 19  TCO Thermique (%)    float64
 20  TCH Thermique (%)    float64
 21  TCO Nucléaire (%)    float64
 22  TCH Nucléaire (%)    float64
 23  TCO Eolien (%)       float64
 24  TCH Eolien (%)       float64
 25  TCO Solaire (%)      float64
 26  TCH Solaire (%)      float64
 27  TCO Hydraulique (%)  float64
 28  TCH Hydraulique (%)  float64
 29  TCO Bioénergies (%)  float64
 30  TCH Bioénergies (%)  float64
 31  Column 30            float64
dtypes: float64(25), int64(1), object(1), str(5)
memory usage: 684.6+ MB

import des librairies panda et numpy

In [ ]:
import pandas as pd
import numpy as np

afficher les types de chaque variable de données

In [6]:
energie.dtypes

Code INSEE région        int64
Région                     str
Nature                     str
Date                       str
Heure                      str
Date - Heure               str
Consommation (MW)      float64
Thermique (MW)         float64
Nucléaire (MW)         float64
Eolien (MW)             object
Solaire (MW)           float64
Hydraulique (MW)       float64
Pompage (MW)           float64
Bioénergies (MW)       float64
Ech. physiques (MW)    float64
Stockage batterie      float64
Déstockage batterie    float64
Eolien terrestre       float64
Eolien offshore        float64
TCO Thermique (%)      float64
TCH Thermique (%)      float64
TCO Nucléaire (%)      float64
TCH Nucléaire (%)      float64
TCO Eolien (%)         float64
TCH Eolien (%)         float64
TCO Solaire (%)        float64
TCH Solaire (%)        float64
TCO Hydraulique (%)    float64
TCH Hydraulique (%)    float64
TCO Bioénergies (%)    float64
TCH Bioénergies (%)    float64
Column 30              float64
dtype: object

In [7]:
#Analayse des données de la colonne Consommation (MW)

In [8]:
energie.loc[energie["Consommation (MW)"].isna()]

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
0,76,Occitanie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,53,Bretagne,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,Île-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28,Normandie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32,Hauts-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,44,Grand Est,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,84,Auvergne-Rhône-Alpes,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,75,Nouvelle-Aquitaine,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,52,Pays de la Loire,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,24,Centre-Val de Loire,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,93,Provence-Alpes-Côte d'Azur,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["Consommation (MW)"].min())
print("valeur maximale : ",energie["Consommation (MW)"].max())

valeur minimale :  0.0
valeur maximale :  15338.0

In [10]:
#Analayse des données de la colonne Consommation (MW)

In [11]:
print("le nombre de ligne NA est de ",energie["Thermique (MW)"].isna().sum())
NbrNA = energie["Thermique (MW)"].isna().sum()
print("% de valeur NA dans la colonne :", (NbrNA/energie.shape[0])*100)

le nombre de ligne NA est de  12
% de valeur NA dans la colonne : 0.0004279649411120241

In [12]:
energie.loc[energie["Thermique (MW)"].isna()]

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
0,76,Occitanie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,53,Bretagne,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,Île-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28,Normandie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32,Hauts-de-France,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,44,Grand Est,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,84,Auvergne-Rhône-Alpes,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,75,Nouvelle-Aquitaine,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,52,Pays de la Loire,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,24,Centre-Val de Loire,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,93,Provence-Alpes-Côte d'Azur,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["Thermique (MW)"].min())
print("valeur maximale : ",energie["Thermique (MW)"].max())

valeur minimale :  -83.0
valeur maximale :  4293.0

In [15]:
#Vérification du nombre de ligne avec des valeurs négatives
print("Il y a",(energie["Thermique (MW)"]<0).sum(),"valeurs négatives")
print("Cela correspond à",((((energie["Thermique (MW)"]<0).sum())/energie.shape[0])*100),"% de valeurs négatives")

Il y a 78327 valeurs négatives
Cela correspond à 2.793434161873459 % de valeurs négatives

In [16]:
#Analyse de la colonne TCO Thermique
print("le nombre de ligne NA est de ",energie["TCO Thermique (%)"].isna().sum())
NbrNA = energie["TCO Thermique (%)"].isna().sum()
print("% de valeur NA dans la colonne :", (NbrNA/energie.shape[0])*100)

#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["TCO Thermique (%)"].min())
print("valeur maximale : ",energie["TCO Thermique (%)"].max())

le nombre de ligne NA est de  1472257
% de valeur NA dans la colonne : 52.5061983588971
valeur minimale :  0.0
valeur maximale :  68.45

In [17]:
#Vérification des colonne TCO Thermique avec une valeur de 0
filtre = energie.loc[energie["TCO Thermique (%)"]==0]
print("Il y a",filtre.shape[0],"ligne avec un TCO Thermique égale à 0")

print("Il y a ",(filtre["Thermique (MW)"]==0).sum(),"ligne avec une valeur 0 pour Thermique MW quand Thermique TCO est égale à 0")

Il y a 155574 ligne avec un TCO Thermique égale à 0
Il y a  155574 ligne avec une valeur 0 pour Thermique MW quand Thermique TCO est égale à 0

In [18]:
#Analyse de la colonne TCH Thermique
print("le nombre de ligne NA est de ",energie["TCH Thermique (%)"].isna().sum())
NbrNA = energie["TCH Thermique (%)"].isna().sum()
print("% de valeur NA dans la colonne :", (NbrNA/energie.shape[0])*100)

#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["TCH Thermique (%)"].min())
print("valeur maximale : ",energie["TCH Thermique (%)"].max())

#Vérification des colonne TCO Thermique avec une valeur de 0
filtre = energie.loc[energie["TCH Thermique (%)"]==0]
print("Il y a",filtre.shape[0],"ligne avec un TCH Thermique égale à 0")

print("Il y a ",(filtre["Thermique (MW)"]==0).sum(),"ligne avec une valeur 0 pour Thermique MW quand Thermique TCH est égale à 0")

le nombre de ligne NA est de  1472256
% de valeur NA dans la colonne : 52.506162695152014
valeur minimale :  0.0
valeur maximale :  96.92
Il y a 155574 ligne avec un TCH Thermique égale à 0
Il y a  155574 ligne avec une valeur 0 pour Thermique MW quand Thermique TCH est égale à 0

In [19]:
# Analyse des colonnes TCO et TCH Nucléaire

In [20]:

print("le nombre de ligne NA est de ",energie["TCO Nucléaire (%)"].isna().sum())
NbrNA = energie["TCO Nucléaire (%)"].isna().sum()
print("% de valeur NA dans la colonne :", (NbrNA/energie.shape[0])*100)

#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["TCO Nucléaire (%)"].min())
print("valeur maximale : ",energie["TCO Nucléaire (%)"].max())

le nombre de ligne NA est de  1560097
% de valeur NA dans la colonne : 55.63890172783712
valeur minimale :  0.0
valeur maximale :  1018.54

In [21]:
#Vérification des colonne TCO Nucléaire avec une valeur de 0
filtre = energie.loc[energie["TCO Nucléaire (%)"]==0]
print("Il y a",filtre.shape[0],"ligne avec un TCO Nucléaire égale à 0")

print("Il y a ",(filtre["Nucléaire (MW)"]==0).sum(),"ligne avec une valeur 0 pour Nucléaire MW quand Nucléaire TCO est égale à 0")

Il y a 478048 ligne avec un TCO Nucléaire égale à 0
Il y a  478048 ligne avec une valeur 0 pour Nucléaire MW quand Nucléaire TCO est égale à 0

In [22]:

#Analyse de la colonne TCH Nucléaire
print("le nombre de ligne NA est de ",energie["TCH Nucléaire (%)"].isna().sum())
NbrNA = energie["TCH Nucléaire (%)"].isna().sum()
print("% de valeur NA dans la colonne :", (NbrNA/energie.shape[0])*100)

#Vérification des valeurs maximales et minimales
print("valeur minimale : ",energie["TCH Nucléaire (%)"].min())
print("valeur maximale : ",energie["TCH Nucléaire (%)"].max())

#Vérification des colonne TCH Nucléaire avec une valeur de 0
filtre = energie.loc[energie["TCH Nucléaire (%)"]==0]
print("Il y a",filtre.shape[0],"ligne avec un TCH Nucléaire égale à 0")

print("Il y a ",(filtre["Nucléaire (MW)"]==0).sum(),"ligne avec une valeur 0 pour Nucléaire MW quand Nucléaire TCH est égale à 0")

le nombre de ligne NA est de  2027136
% de valeur NA dans la colonne : 72.29526157217201
valeur minimale :  0.0
valeur maximale :  102.01
Il y a 11008 ligne avec un TCH Nucléaire égale à 0
Il y a  11008 ligne avec une valeur 0 pour Nucléaire MW quand Nucléaire TCH est égale à 0